name: fmt

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18.1'
    - run: make gofmt-check
