name: staticcheck

on:
  - push
  - pull_request

jobs:
  staticcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18.1'
    - run: go install honnef.co/go/tools/cmd/staticcheck@latest
    - run: make staticcheck
